# Grammar for guppylang: https://github.com/CQCL/guppylang

DECORATOR = "@guppy";

QUBIT_TYPE_ANNOT = "qubit";

TAB = "\t";

imports = "from guppylang.decorator import guppy"
        "from guppylang.std.angles import angle, pi"
        "from guppylang.std.builtins import array, owned, py"
        "from guppylang.std.option import Option, nothing, some"
        "from guppylang.std.quantum import ("
            "cz,"
            "discard,"
            "h,"
            "measure,"
            "qubit,"
            "ry,"
            "rz"
        ")";

program = imports NEWLINE subroutines NEWLINE block NEWLINE compiler_call;

subroutines = (block NEWLINE)*;

block     = circuit_def NEWLINE body NEWLINE;

body = (statement NEWLINE)+ return_statement;

circuit_def = DECORATOR NEWLINE "def " circuit_name "(" qubit_defs "):";

qubit_defs = (qubit_def)+;

qubit_def = qubit_def_singular | qubit_def_register;

qubit_def_singular = qubit_name " : " QUBIT_TYPE_ANNOT;

qubit_def_register = qreg_name " : array[" QUBIT_TYPE_ANNOT ", " qreg_size "]";

qubit = singular_qubit_apply | register_qubit_apply;

singular_qubit_apply = qubit_name;

register_qubit_apply = qubit_name "[" qubit_index "]"; 

return_statement = "return";
