expr = term (("+" | "-") expr)*;
#term = factor "*" term | factor "/" term | factor ;
#factor = integer | "(" expr ")" ;
#integer = [a-zUu] ;

# DECIMAL_LITERAL: [1-9] [0-9]* ( ( [U-u]? [Ll]* ) | ( [Ll]* [Uu]? ) ) ;
