# trying to fix up a pytket grammar that could be used

circuit     = circuit_def qreg_defs statements;

qreg_defs = (qreg_def)+;

statements = (statement)+;

circuit_def = circuit_name EQUALS "Circuit" LPAREN num_index_qubits RPAREN;

qreg_def    = qreg_name EQUALS circuit_name ".add_q_register" LPAREN qreg_size RPAREN;

statement   = gate_application;

gate_application = 
    circuit_name DOT gate_name gate_application_kind
    ;

gate_application_kind = 
    LPAREN qubit_list RPAREN 
    | LPAREN float_literal COMMA qubit_list RPAREN
    ;

gate_name   = X | Y | Z | H | CX | CCX | Rz | Rx | Ry | U1 | U2 | U3;
qubit_list  = qubit (COMMA SPACE qubit)*;

parameter_list = parameter (COMMA SPACE parameter)*;
parameter      = float_literal | "Symbol(\"" identifier SINGLE_QUOTE RPAREN;

identifier    = "test";
int_literal   = 1-9 (digit)+;
float_literal = digit DOT (digit)*;
letter        = a-z | A-Z;
digit         = 0-9;

