# trying to fix up a pytket grammar that could be used

(*
    tokens like NEWLINE and RPAREN are defined in the tokens.bnf file
*)

program = imports NEWLINE subroutines NEWLINE circuit NEWLINE compiler_call;

# subroutines = (circuit NEWLINE circuit_name "=" circuit_name ".to_gate()" NEWLINE)*;

subroutines = (circuit)*;

circuit     = circuit_def NEWLINE qreg_defs NEWLINE statements NEWLINE;

qreg_defs = (qreg_def NEWLINE)+; # def /n | def /n def /n | def /n def /n def /n .....

statements = (statement NEWLINE)+;

circuit_def = circuit_name " = Circuit()";

qreg_def    = qreg_name EQUALS circuit_name ".add_q_register" LPAREN qreg_size RPAREN;

statement   = gate_application;

gate_application = 
    circuit_name DOT gate_name gate_application_kind
    | circuit_name ".append(" subroutine ",([" qubit_list "]))"  
    ;

gate_application_kind = 
    LPAREN qubit_list RPAREN 
    | LPAREN float_literal COMMA qubit_list RPAREN
    ;

gate_name   = X | Y | Z | H | CX | CCX | Rz | Rx | Ry | U1 | U2 | U3;
qubit_list  = qubit (COMMA SPACE qubit)*;
qubit = qubit_name "[" qubit_index "]";

parameter_list = parameter (COMMA SPACE parameter)*;
parameter      = float_literal | "Symbol(\"" identifier SINGLE_QUOTE RPAREN;

