# Qiskit grammar
program = imports NEWLINE subroutines NEWLINE circuit NEWLINE compiler_call NEWLINE;

subroutines = (circuit NEWLINE circuit_name "=" circuit_name ".to_gate()" NEWLINE)*;

circuit = circuit_def NEWLINE qreg_defs NEWLINE body;

qreg_defs = (qreg_def NEWLINE)+;

body = (statement NEWLINE)+;

circuit_def = circuit_name " = QuantumCircuit()";

# In Qiskit, qreg are added in two separate lines
qreg_def = qreg_decl NEWLINE qreg_append;
qreg_decl = qreg_name EQUALS "QuantumRegister" LPAREN qreg_size RPAREN;
qreg_append = circuit_name ".add_register" LPAREN qreg_name RPAREN;

statement = gate_application;

gate_application = 
    circuit_name DOT gate_name gate_application_kind
    | circuit_name ".append(" subroutine ",[" qubit_list "])" 
    ;

gate_application_kind = 
    LPAREN qubit_list RPAREN 
    | LPAREN float_literals COMMA qubit_list RPAREN
    ;

float_literals = float_literal | float_literal COMMA float_literal | float_literal COMMA float_literal COMMA float_literal;

gate_name = x | y | z | h | cx | ccx | rz | rx | ry | u;
qubit_list = qubit (COMMA SPACE qubit)*;
qubit = qubit_name "[" qubit_index "]";

parameter_list = parameter (COMMA SPACE parameter)*;
parameter =  
    float_literal 
    | "Symbol(\"" identifier SINGLE_QUOTE RPAREN;