# Qiskit grammar
program = imports "\n" circuit "\n" compiler_call;

circuit = circuit_def "\n" qreg_defs "\n" statements "\n";

qreg_defs = (qreg_def "\n")+;

statements = (statement "\n")+;

circuit_def = circuit_name " = QuantumCircuit()";

# In Qiskit, qreg are added in two separate lines
qreg_def = qreg_decl "\n" qreg_append;
qreg_decl = qreg_name EQUALS "QuantumRegister" LPAREN qreg_size RPAREN;
qreg_append = circuit_name ".add_register" LPAREN qreg_name RPAREN;

statement = gate_application;

gate_application = 
    circuit_name DOT gate_name gate_application_kind
    ;

gate_application_kind = 
    LPAREN qubit_list RPAREN 
    | LPAREN float_literal COMMA qubit_list RPAREN
    ;

gate_name   = x | y | z | h | cx | ccx | rz | rx | ry | u;
qubit_list  = qubit (COMMA SPACE qubit)*;

parameter_list = parameter (COMMA SPACE parameter)*;
parameter      = float_literal | "Symbol(\"" identifier SINGLE_QUOTE RPAREN;