# TOKENS USED BY EVERY GRAMMAR

LPAREN: "(";
RPAREN: ")";
LBRACK: "[";
RBRACK: "]";
LBRACE: "{";
RBRACE: "}";
COMMA: ",";
SPACE: " ";
DOT: ".";
SINGLE_QUOTE: "\'";
DOUBLE_PIPE: "||";
DOUBLE_QUOTE: "\"";
DOUBLE_AMPERSAND: "&&";
EQUALS: " = ";
NEWLINE: "\n";
SEMICOLON : ";";
COLON: ":";
ARROW: '->';
PLUS: '+';
DOUBLE_PLUS: '++';
MINUS: '-';
ASTERISK: '*';
DOUBLE_ASTERISK: '**';
SLASH: '/';
PERCENT: '%';
PIPE: '|';
DOUBLE_PIPE: '||';
AMPERSAND: '&';
CARET: '^';
AT: '@';
TILDE: '~';
EXCLAMATION_POINT: '!';